version: '3.8'
name: ipuserver

services:
  latex-server:
    container_name: latex-server
    build: .
    ports:
      - "3001:80"
    restart: unless-stopped
    volumes:
      - ./fonts:/usr/local/share/fonts/project:ro
      - fonts_api:/usr/local/share/fonts/api
    networks:
      - ipuserver_webserver

volumes:
  fonts_api:

networks:
  # ipuserver_internal:
  #   external: true
  ipuserver_webserver:
    external: true